package com.adirahav.diraleashkaa.common

object Const {

    internal const val CITY: String = "city"
    internal const val CITY_ELSE: String = "cityElse"
    internal const val ADDRESS: String = "address"
    internal const val APARTMENT_TYPE: String = "apartmentType"
    internal const val PRICE: String = "price"
    internal const val EQUITY: String = "equity"
    internal const val INCOMES: String = "incomes"
    internal const val POSSIBLE_MONTHLY_REPAYMENT_PERCENT: String = "possibleMonthlyRepaymentPercent"
    internal const val COMMITMENTS: String = "commitments"
    internal const val LAWYER_PERCENT: String = "lawyerPercent"
    internal const val LAWYER_CUSTOM_VALUE: String = "lawyerCustomValue"
    internal const val REAL_ESTATE_AGENT_PERCENT: String = "realEstateAgentPercent"
    internal const val REAL_ESTATE_AGENT_CUSTOM_VALUE: String = "realEstateAgentCustomValue"
    internal const val BROKER_MORTGAGE: String = "brokerMortgage"
    internal const val REPAIRING: String = "repairing"
    internal const val RENT_PERCENT: String = "rentPercent"
    internal const val RENT_CUSTOM_VALUE: String = "rentCustomValue"
    internal const val LIFE_INSURANCE: String = "lifeInsurance"
    internal const val STRUCTURE_INSURANCE: String = "structureInsurance"
    internal const val MORTGAGE_PERIOD: String = "mortgagePeriod"
    internal const val INDEX_PERCENT: String = "indexPercent"
    internal const val INTEREST_PERCENT: String = "interestPercent"
    internal const val INTEREST_IN_5_YEARS_PERCENT: String = "interestIn5YearsPercent"
    internal const val INTEREST_IN_10_YEARS_PERCENT: String = "interestIn10YearsPercent"
    internal const val AVERAGE_INTEREST_AT_TAKING_PERCENT: String = "averageInterestAtTakingPercent"
    internal const val AVERAGE_INTEREST_AT_MATURITY_PERCENT: String = "averageInterestAtMaturityPercent"
    internal const val FORECAST_ANNUAL_PRICE_INCREASE_PERCENT: String = "forecastAnnualPriceIncreasePercent"
    internal const val SALES_COSTS_PERCENT: String = "salesCostsPercent"
    internal const val DEPRECIATION_FOR_TAX_PURPOSES_PERCENT: String = "depreciationForTaxPurposesPercent"
    internal const val SALE_YEARS_PERIOD: String = "saleYearsPeriod"

}