package com.adirahav.diraleashkaa.common

object Const {

    internal const val CITY: String = "city"
    internal const val CITY_ELSE: String = "city_else"
    internal const val ADDRESS: String = "address"
    internal const val APARTMENT_TYPE: String = "apartment_type"
    internal const val PRICE: String = "price"
    internal const val EQUITY: String = "equity"
    internal const val INCOMES: String = "incomes"
    internal const val POSSIBLE_MONTHLY_REPAYMENT_PERCENT: String = "possible_monthly_repayment_percent"
    internal const val COMMITMENTS: String = "commitments"
    internal const val LAWYER_PERCENT: String = "lawyer_percent"
    internal const val LAWYER_CUSTOM_VALUE: String = "lawyer_custom_value"
    internal const val REAL_ESTATE_AGENT_PERCENT: String = "real_estate_agent_percent"
    internal const val REAL_ESTATE_AGENT_CUSTOM_VALUE: String = "real_estate_agent_custom_value"
    internal const val BROKER_MORTGAGE: String = "broker_mortgage"
    internal const val REPAIRING: String = "repairing"
    internal const val RENT_PERCENT: String = "rent_percent"
    internal const val RENT_CUSTOM_VALUE: String = "rent_custom_value"
    internal const val LIFE_INSURANCE: String = "life_insurance"
    internal const val STRUCTURE_INSURANCE: String = "structure_insurance"
    internal const val MORTGAGE_PERIOD: String = "mortgage_period"
    internal const val INDEX_PERCENT: String = "index_percent"
    internal const val INTEREST_PERCENT: String = "interest_percent"
    internal const val INTEREST_IN_5_YEARS_PERCENT: String = "interest_in_5_years_percent"
    internal const val INTEREST_IN_10_YEARS_PERCENT: String = "interest_in_10_years_percent"
    internal const val AVERAGE_INTEREST_AT_TAKING_PERCENT: String = "average_interest_at_taking_percent"
    internal const val AVERAGE_INTEREST_AT_MATURITY_PERCENT: String = "average_interest_at_maturity_percent"
    internal const val FORECAST_ANNUAL_PRICE_INCREASE_PERCENT: String = "forecast_annual_price_increase_percent"
    internal const val SALES_COSTS_PERCENT: String = "sales_costs_percent"
    internal const val DEPRECIATION_FOR_TAX_PURPOSES_PERCENT: String = "depreciation_for_tax_purposes_percent"
    internal const val SALE_YEARS_PERIOD: String = "sale_years_period"

}